name: Generate and Release Assets

on:
  workflow_dispatch:

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Generate Assets
        id: generate_assets
        run: npm run generate-assets

      - name: Check for JSON and YAML Archives
        id: check_artifacts
        run: |
          if [ -f artifacts/json-files.zip ] && [ -f artifacts/yaml-files.zip ]; then
            echo "artifacts_exist=true" >> $GITHUB_ENV
          else
            echo "artifacts_exist=false" >> $GITHUB_ENV
          fi

      - name: Create Release
        id: create_release
        if: env.artifacts_exist == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}.${{ github.sha }}
          release_name: "Release v${{ github.run_number }}.${{ github.sha }}"
          draft: false
          prerelease: true
          body: "This release includes assets generated by the automated build process. 
            The archives contain the latest JSON and YAML files for this version."

      - name: Upload JSON Archive
        if: env.artifacts_exist == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/json-files.zip
          asset_name: "json-files.zip"
          asset_content_type: application/zip

      - name: Upload YAML Archive
        if: env.artifacts_exist == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/yaml-files.zip
          asset_name: "yaml-files.zip"
          asset_content_type: application/zip

      - name: Cleanup Artifacts
        if: env.artifacts_exist == 'true'
        run: |
          rm -f artifacts/json-files.zip artifacts/yaml-files.zip

      - name: No Artifacts Found
        if: env.artifacts_exist == 'false'
        run: echo "No artifacts were created, so no release was made."
